#  Available Hydra Lab Variables In Script:
#  $HydraLab_TestResultFolderPath: The full path of the test result folder
#  $HydraLab_deviceUdid: The UDID of mobile device. (For Android, it will be equal to the serial number)
app:
  device:
    monitor:
      - type: WINDOWS
        enabled: true
      - type: ANDROID
        enabled: true
      - type: IOS
        enabled: true
  device-script:
    commands:
      - type: ADBShell
        when: setUp
        suite-class-matcher: '.*'
        inline: |
          test command 1
      - type: ADBShell
        when: setUp
        suite-class-matcher: '.*test.*'
        inline: |
          test command 2
          test command 3
      - type: AgentShell
        when: setUp
        suite-class-matcher: '.*test.*'
        inline: |
          test command 4
      - type: ADBShell
        when: tearDown
        suite-class-matcher: 'com.microsoft.test'
        inline: |
          test command 5
      - type: AgentShell
        when: tearDown
        suite-class-matcher: 'com.microsoft.test'
        inline: |
          test command 6
          test command 7