app:
  device-script:
    commands:
      - type: ADBShell
        when: setUp
        suite-class-matcher: '.*'
        inline: |
          test command 1
      - type: ADBShell
        when: setUp
        suite-class-matcher: '.*test.*'
        inline: |
          test command 2
          test command 3
      - type: AgentShell
        when: setUp
        suite-class-matcher: '.*test.*'
        inline: |
          test command 4
      - type: ADBShell
        when: tearDown
        suite-class-matcher: 'com.microsoft.test'
        inline: |
          test command 5
      - type: AgentShell
        when: tearDown
        suite-class-matcher: 'com.microsoft.test'
        inline: |
          test command 6
          test command 7